config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights:
      branch: main
      repo: https://github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-tomato-angora.sh
        container: qc.acc_homely-khaki-ant
  QC.Doc:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-corn-hummingbird.sh
        container: qc.doc_sloppy-azure-dolphin
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-burgundy-macaw.sh
        container: qc.doc_droopy-mustard-emu
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-linen-spitz.sh
        container: qc.doc_nerdy-lilac-cichlid
  QC.Lic:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lemon-tapir.sh
        container: qc.lic_hazy-ruby-dragonfly
  QC.Met:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-yellow-buffalo.sh
        container: qc.met_flaky-purple-tamarin
  QC.Sty:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cerulean-hornet.sh
        container: qc.sty_chummy-pear-echidna
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-sapphire-dragonfly.sh
        container: qc.sty_lovely-cardinal-insect
  QC.Ver:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-tan-earwig.sh
        container: qc.ver_sleazy-aquamarine-binturong
timeout: 5400
