config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights:
      branch: main
      repo: https://github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-rust-deer.sh
        container: qc.acc_sickly-apricot-tamarin
  QC.Doc:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-lime-stoat.sh
        container: qc.doc_nippy-mustard-cheetah
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-persimmon-booby.sh
        container: qc.doc_baggy-sangria-ladybird
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-ecru-uakari.sh
        container: qc.doc_fuzzy-sangria-wasp
  QC.Lic:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-orange-mandrill.sh
        container: qc.lic_smelly-lime-koala
  QC.Met:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.surly-bistre-meerkat.sh
        container: qc.met_scummy-thistle-sponge
  QC.Sty:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-wheat-chin.sh
        container: qc.sty_sleepy-rose-eagle
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-ivory-boar.sh
        container: qc.sty_stinky-zucchini-dalmatian
  QC.Ver:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-access-rights get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-azure-quoll.sh
        container: qc.ver_sleazy-beige-tortoise
timeout: 5400
